version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scrapper
    volumes:
      - .:/app
    working_dir: /app
    command: python scrapper/main.py
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/lib/chromium/chromedriver
