name: BRVM Scraper

on:
  schedule:
    - cron: '0 15 * * 1-5'  # Tous les jours de la semaine à 15h UTC (10h CI)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Docker (latest for Ubuntu 24.04)
        uses: docker-practice/actions-setup-docker@v1

      - name: Build and run Docker container
        run: |
          docker build -t brvm_scraper .
          docker run --rm \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_HOST=$DB_HOST \
            -e DB_PORT=$DB_PORT \
            -e DB_NAME=$DB_NAME \
            brvm_scraper
